server:
  port: 18083
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 604800
      persistent: true
      store-dir: "/../session"
      cookie:
        max-age: 604800
#        #secure: true
#        #http-only: true
  tomcat:
    max-swallow-size: 20MB
  error:
    include-message: always
    whitelabel:
      enabled: false  # 기본 오류 페이지 비활성화
    include-stacktrace: never
    path: /error
#  ssl: 
#    enabled: true
#    key-store: "classpath:keystore.p12"
#    key-store-type: "PKCS12"
#    key-store-password: "changeit"
  http:
    port: 18083
    
springdoc:
  show-actuator: true
#  use-management-port: true
  
#  version: v1.0.0
#  packages-to-scan: com
#  swagger-ui:
#    path: /swagger,
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /api-docs/json


          
spring:
  main:
    allow-bean-definition-overriding: true 
    
  output:
    ansi:
      enabled: always
  web:
    resources:
      static-locations: file:../upload/  
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      location: multipartlocation
      max-file-size: 10MB
      max-request-size: 20MB
  
  devtools:
    livereload:
      enabled: true

  mvc:
    contentnegotiation:
      favor-parameter: true
      favor-path-extension: true
      media-types: 
        xls: application/x-ms-excel
    hiddenmethod:
      filter:
        enabled: true

    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
    pathmatch:
      matching-strategy: ant-path-matcher

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:p6spy:mysql://localhost/bondang2.0
#    url: jdbc:p6spy:mysql://210.90.113.33:3306/bondang2.0
    url: jdbc:log4jdbc:mysql://211.57.200.87:3306/new_idikorea?zeroDateTimeBehavior=convertToNull


    username: root
#    password: 1234
#    username: root
    password: brighten0701)&)!
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: none #변경금지
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        format_sql: false
#        show_sql: false

  jackson:
    serialization:
#      write-date-keys-as-timestamps: false
      fail-on-empty-beans: false

auth:
  masterKey: "0701"
  upload: '../upload'
  file-server-url : 'idikorea1.cdn3.cafe24.com'
  permitId : brighten
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.brighten.idi.module.*.dto
  mapper-locations:
  - classpath:static/mapper/*.xml
  

logging:
  level:
    brighten: error
#    web: TRACE
#    org:
#      springframework:
#        web: TRACE
#      hibernate:
#        type:
#          descriptor:
#            sql: trace


